apiVersion: v1
kind: Pod
metadata:
  name: limitrange-over-memory-pod
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: "10m"
        memory: "16Mi"
      limits:
        cpu: "100m"
        memory: "500Mi"
