apiVersion: v1
kind: Pod
metadata:
  name: memory-over-pod
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: "200m"
        memory: "300Mi"
      limits:
        cpu: "200m"
        memory: "3000Mi"

